name: Deploy Cloudflare Worker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Debug
        run: |
          echo "CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}"
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }} 
          secrets: |
            ELASTIC_APM_SERVER_URL
        env: 
          ELASTIC_APM_SERVER_URL: ${{ secrets.ELASTIC_APM_URL }}


          

